name: Prevent ID Theft
favicon: null
layout_spectrum: 0.8056227941997349
typography_spectrum: 0.14842678979039192
title: Prevent ID Theft for your minor
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.3442454026080668
  lightness: 0.30750728165730834
  saturation: 0.9542594205122441
  rhythmicContrast: 0.17182773421518505
purpose: []
